#ifndef DNAND_CLID_H
#define DNAND_CLID_H
/*
 * This software is contributed or developed by KYOCERA Corporation.
 * (C) 2013 KYOCERA Corporation
 */
#include <linux/types.h>

typedef enum
{
  DNAND_ID_KERNEL_0 = 0,
  DNAND_ID_KERNEL_1,
  DNAND_ID_KERNEL_2,
  DNAND_ID_KERNEL_3,
  DNAND_ID_KERNEL_4,
  DNAND_ID_KERNEL_5,
  DNAND_ID_KERNEL_6,
  DNAND_ID_KERNEL_7,
  DNAND_ID_KERNEL_8,
  DNAND_ID_KERNEL_9,
  DNAND_ID_KERNEL_10,
  DNAND_ID_KERNEL_11,
  DNAND_ID_KERNEL_12,
  DNAND_ID_KERNEL_13,
  DNAND_ID_KERNEL_14,
  DNAND_ID_KERNEL_15,
  DNAND_ID_KERNEL_16,
  DNAND_ID_KERNEL_17,
  DNAND_ID_KERNEL_18,
  DNAND_ID_KERNEL_19,
  DNAND_ID_KERNEL_20,
  DNAND_ID_KERNEL_21,
  DNAND_ID_KERNEL_22,
  DNAND_ID_KERNEL_23,
  DNAND_ID_KERNEL_24,
  DNAND_ID_KERNEL_53 = 53,
  DNAND_ID_KERNEL_54,
  DNAND_ID_ENUM_MAX
} dnand_id_enum_type;

#endif
